#!/bin/sh
# fhs.sh - a look at the top of the Linux directory tree
echo "--- the usr-merge: /bin, /sbin and /lib are symbolic links into /usr"
ls -ld /bin /sbin /lib /lib64
echo "--- which file system holds which top-level directory:"
for d in / /usr /var /etc /tmp /run /proc /sys /dev/shm; do
  printf '%-9s %s\n' "$d" "$(findmnt -n -o FSTYPE,SOURCE -T "$d" | head -1)"
done
echo "--- the virtual file systems in /proc/mounts (no device behind them):"
grep -E '^(proc|sysfs) ' /proc/mounts
echo "--- /proc is generated by the kernel: one directory per process, and more"
ls -d /proc/[0-9]* | wc -l
ls -l /proc/mounts
head -3 /proc/partitions
echo "--- sizes of the big three:"
du -sh /usr /var /etc 2>/dev/null
